
export const quizModel={
    "integrityServiceId": 0,
    "subjectId": 0,
    "status": 1,
    "channelId": 0,
    "videoId": 0,
    "round": 0,
    "quizType": 1,
    "typeForm": 1,
    "code": "",
    "name": "",
    "description": "",
    "suggest": "",
    "content": "",
    "difficulty": 1,
    "numberOfQuestion": 0,
    "mediaContentType": 1,
    "imageUrl": "",
    "duration": 0,
    "medias": "",
    "enableScore": true,
    "correctAnswer": "",
    "startTime": 0,
    "endTime": 0,
    "paymentType": 1,
    "order": 0,
    "isSaveResult": true,
    "isShowTop": true,
    "bonusPoints": 0,
    "addGifts": true,
    "addPointsWinner": 0,
    "isRandomQuestions": true,
    "isRandomAnswers": true,
    "enableSound": true,
    "musicLink": "",
    "tags": "",
    "themeType": 0,
    "enableTimer": true,
    "enableChangeResults": true,
    "isShowAnswers": true,
    "enableQuestionSkip": true,
    "minScorePass": 0.1,
    "winnersCount": 0,
    "chooseWinnerMethod": 0,
    "totalRound": 0,
    "userLimit": 0,
    "isShowCheck": 0,
    "price": 0.1,
    "questions":[],
    "uploadRequest": {
        "fileName": "abc",
        "extension": "abc",
        "uploadType": 0,
        "data": "abc"
    }

}